# Generated by Django 4.1.5 on 2023-06-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_borrowerphoto'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principleAmount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amountDue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.member')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.member'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='durationPer',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='year', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_cycle',
            field=models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Defaulted', 'Defaulted'), ('Denied', 'Denied'), ('Write Off', 'Write Off'), ('Debt Review', 'Debt Review'), ('Not Taken Up', 'Not Taken Up')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyPayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principlePayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymentDate', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Cleared', 'Cleared'), ('Missed', 'Missed'), ('Arears', 'Arears')], default='Open', max_length=50)),
                ('loanAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loanaccount')),
            ],
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loan'),
        ),
    ]
