# Generated by Django 4.1.5 on 2023-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loanaccount_alter_loan_borrower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
