# Generated by Django 4.1.5 on 2023-07-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_loanpaymentsreceipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Defaulted', 'Defaulted'), ('Repaying', 'Repaying'), ('Denied', 'Denied'), ('Write Off', 'Write Off'), ('Debt Review', 'Debt Review'), ('Not Taken Up', 'Not Taken Up')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Cleared', 'Cleared'), ('Missed', 'Missed'), ('Arrears', 'Arrears')], default='Open', max_length=50),
        ),
        migrations.CreateModel(
            name='LoanPaymentII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyPayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principlePayment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymentDate', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Cleared', 'Cleared'), ('Missed', 'Missed'), ('Arrears', 'Arrears')], default='Open', max_length=50)),
                ('loanAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loanaccount')),
            ],
        ),
    ]
