# Generated by Django 4.1.5 on 2023-06-21 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scanned_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('ld_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specify', 'Not Specify')], max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('dob', models.DateField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(max_length=100)),
                ('te_id', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specify', 'Not Specify')], max_length=50, null=True)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=50, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('province', models.CharField(max_length=150, null=True)),
                ('landlinePhone', models.IntegerField(null=True)),
                ('workStatus', models.CharField(choices=[('Employee', 'Employee'), ('Goverment Employee', 'Goverment Employee'), ('Private Employee', 'Private Employee'), ('Owner', 'Owner'), ('Student', 'Student'), ('Overseas worker', 'Overseas worker'), ('Pensioner', 'Pensioner'), ('Unemployed', 'Unemployed')], max_length=50, null=True)),
                ('borrowerPhoto', models.ImageField(null=True, upload_to='photos/')),
                ('desc', models.TextField(null=True)),
                ('borrowerFiles', models.ManyToManyField(blank=True, null=True, to='user.scannedfile')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Oficers', to='user.officer')),
            ],
        ),
    ]
