# Generated by Django 4.1.5 on 2023-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borrowerPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
